### ISSUE TITLE
AMP compatibility

### ISSUE THREAD

**Issue by swissspidy** [thatplugincompany/coblocks-theme#1]
I've been using this theme for a few days now on my personal website and really like it so far.

Unfortunately it's not compatible with the [AMP WordPress plugin](https://wordpress.org/plugins/amp/). Is there any chance that you are interested in making CoBlocks AMP-compatible?

If so, I'd be happy to contribute a PR to get things started.

**Comment by richtabor** [comment]
Hey @swissspidy, sure thing! That'd be pretty cool really!
