### ISSUE TITLE
Blank Page Template

### ISSUE THREAD

**Issue by phpbits** [thatplugincompany/coblocks-theme#11]
@richtabor While experimenting with layouts, I think it would be really great if we have blank canvas so users can set full height hero image at the top and create footers :) What do you think?

<img width="1269" alt="screen shot 2019-02-26 at 1 47 09 pm" src="https://user-images.githubusercontent.com/3365507/53390264-9442de80-39cd-11e9-80bc-ba822bdf746c.png">

**Comment by richtabor** [comment]
@phpbits How do you envision this working? Would wide and full alignments do anything if the blocks were already displayed at full width on the page template?

**Comment by phpbits** [comment]
@richtabor I'm thinking just the content area, no header and footer. We can set the width using our blocks. The use cases would be for one-page site and landing pages.

**Comment by richtabor** [comment]
Ah, so a page template without a header and footer, solely based on the block content?

**Comment by phpbits** [comment]
@richtabor Yeah :) Would be perfect for our layouts.
