### ISSUE TITLE
Dark mode is persistent when system preferences are set to dark mode

### ISSUE THREAD

**Issue by RobStino** [thatplugincompany/coblocks-theme#17]
Hey all,
I realise that this is actually a pretty clever little feature, but it actually got in the way of what I was trying to do with the theme.
I had the dark mode option disabled in the Customizer as I wanted to build out a site with the white/light style. However, as my system preferences (MacOS) are set to dark mode, Chrome and the theme pick this up and auto-apply the dark mode styling.
This is a great feature, but one I think could be optional and handled by an additional setting in the customizer.

**Steps to reproduce**
1. Set system preferences to dark mode
2. In the customiser disable "Night Mode"
3. Observe that the the site remains in dark (night) mode

**Comment by Satlantisy** [comment]
> Hey all,
> I realise that this is actually a pretty clever little feature, but it actually got in the way of what I was trying to do with the theme.
> I had the dark mode option disabled in the Customizer as I wanted to build out a site with the white/light style. However, as my system preferences (MacOS) are set to dark mode, Chrome and the theme pick this up and auto-apply the dark mode styling.
> This is a great feature, but one I think could be optional and handled by an additional setting in the customizer.
> 
> **Steps to reproduce**
> 
> 1. Set system preferences to dark mode
> 2. In the customiser disable "Night Mode"
> 3. Observe that the the site remains in dark (night) mode

I totally agree with you RobStino. As macOS can choose either light, dark or automatic, if the CoBlocks theme can choose it as well, that'd be awesome.

I found a temporary solution as below:

1. Backup you theme in case anything wrong.
2. Get into your theme directory, open style.css file, search "prefers-color-scheme: dark" and delete all code relate to it.
3. Open inc->customiser->defaults.php, change the value of "night-mode" to "false"
4. Save it and refresh your page.

It works in my website, hope it helps yours.

Regards
Alan

**Comment by RobStino** [comment]
Hey @Satlantisy 
Dark, light, auto is a great idea for this.
Thanks for the solution as well. Will check it out via a Child theme.

**Comment by ms-studio** [comment]
Thanks @Satlantisy for the info.

Of course editing the theme file is not a long-term approach, as every theme update will erase the modified files. I would also prefer the Night mode to be an option that can be disabled.
