### ISSUE TITLE
WordPress Social Icon Broken

### ISSUE THREAD

**Issue by seb86** [thatplugincompany/coblocks-theme#4]
Hi @richtabor 

When using the social menu to add your WordPress.org profile, the icon is not positioned correctly but only in the Firefox browser. Strange I know. Any chance of a quick patch?

![wp icon broken](https://user-images.githubusercontent.com/497406/46754780-91b44680-ccc3-11e8-8fe0-7ba80c59650a.png)

**Comment by richtabor** [comment]
Hey @seb86 What version of the theme are you running?

**Comment by seb86** [comment]
I am using v1.1.4

**Comment by richtabor** [comment]
Mhmm, I'm not running into that same issue. Testing with Safari, Chrome and Firefox. Do you have an live URL? 

<img width="351" alt="screen shot 2018-10-10 at 4 46 38 pm" src="https://user-images.githubusercontent.com/1813435/46765068-15facf80-ccac-11e8-8437-5814e96e9941.png">

**Comment by seb86** [comment]
https://sebdumont.xyz/

**Comment by seb86** [comment]
Using Firefox Quantum v62.0.3

**Comment by seb86** [comment]
Not sure if that helps.

**Comment by richtabor** [comment]
Ah, I'm seeing the opposite — where it's messed up on only in Firefox .

**Comment by richtabor** [comment]
Found it. 👍

**Comment by seb86** [comment]
I have deactivated all my Firefox extensions and cleared my cached. Still no change.

**Comment by richtabor** [comment]
With the recent commit?

**Comment by richtabor** [comment]
I'm still seeing the old SVG icon markup on your site currently.

**Comment by seb86** [comment]
My last comment was delayed. I have updated my site now and cleared the cache. Let me know if it looks good for you now.
