### ISSUE TITLE
Request: Add Slack icon to the sprite.svg file

### ISSUE THREAD

**Issue by seb86** [thatplugincompany/coblocks-theme#5]
Would be super great if Slack was added too. 👍

**Comment by richtabor** [comment]
@seb86 What would be the url?

**Comment by seb86** [comment]
A private slack channel like https://poststatus.slack.com for example.

**Comment by seb86** [comment]
Any sub-domain for slack.com

**Comment by seb86** [comment]
Thank you @richtabor
